// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: time_teller.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timezone string `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *TellRequest) Reset() {
	*x = TellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_time_teller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TellRequest) ProtoMessage() {}

func (x *TellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_time_teller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TellRequest.ProtoReflect.Descriptor instead.
func (*TellRequest) Descriptor() ([]byte, []int) {
	return file_time_teller_proto_rawDescGZIP(), []int{0}
}

func (x *TellRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type TimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TimeResponse) Reset() {
	*x = TimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_time_teller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResponse) ProtoMessage() {}

func (x *TimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_time_teller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResponse.ProtoReflect.Descriptor instead.
func (*TimeResponse) Descriptor() ([]byte, []int) {
	return file_time_teller_proto_rawDescGZIP(), []int{1}
}

func (x *TimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_time_teller_proto protoreflect.FileDescriptor

var file_time_teller_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x29, 0x0a, 0x0b,
	0x54, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x4b, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12,
	0x3d, 0x0a, 0x0c, 0x57, 0x68, 0x61, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x73, 0x49, 0x74, 0x12,
	0x14, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x54, 0x65, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_time_teller_proto_rawDescOnce sync.Once
	file_time_teller_proto_rawDescData = file_time_teller_proto_rawDesc
)

func file_time_teller_proto_rawDescGZIP() []byte {
	file_time_teller_proto_rawDescOnce.Do(func() {
		file_time_teller_proto_rawDescData = protoimpl.X.CompressGZIP(file_time_teller_proto_rawDescData)
	})
	return file_time_teller_proto_rawDescData
}

var file_time_teller_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_time_teller_proto_goTypes = []interface{}{
	(*TellRequest)(nil),  // 0: example.TellRequest
	(*TimeResponse)(nil), // 1: example.TimeResponse
}
var file_time_teller_proto_depIdxs = []int32{
	0, // 0: example.TimeTeller.WhatTimeIsIt:input_type -> example.TellRequest
	1, // 1: example.TimeTeller.WhatTimeIsIt:output_type -> example.TimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_time_teller_proto_init() }
func file_time_teller_proto_init() {
	if File_time_teller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_time_teller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_time_teller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_time_teller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_time_teller_proto_goTypes,
		DependencyIndexes: file_time_teller_proto_depIdxs,
		MessageInfos:      file_time_teller_proto_msgTypes,
	}.Build()
	File_time_teller_proto = out.File
	file_time_teller_proto_rawDesc = nil
	file_time_teller_proto_goTypes = nil
	file_time_teller_proto_depIdxs = nil
}
